project:
  type: book
  output-dir: docs

execute:
  echo: true
  warning: false
  message: false

book:
  title: "Bends Before The Break: Understanding Recessions Through the Yield Curve"
  author:
    - Vaishnavi Kannan (vk2580)
    - Raghav Sampath (rs4760)
  repo-url: https://github.com/thehyperpineapple/bendsbeforethebreak
  date: today
  page-footer:
    right: |
      This book was built with <a href="https://quarto.org/">Quarto</a>.
  repo-actions: [edit, issue]
  chapters:
    - index.qmd
    - data.qmd
    - results.qmd
    - conclusion.qmd

format:
  html:
    theme: lux
    code-fold: true
